core/urls.py
from django.urls import path
from . import views


app_name = 'core'
urlpatterns = [
    path('movies/', views.MovieList.as_view(), name='movie_list'),
    path('movies/top', views.TopMovies.as_view(), name='top_movies'),
    path('movie/<int:pk>/', views.MovieDetail.as_view(), name='movie_detail'),
    path('movie/<int:movie_id>/vote/', views.CreateVote.as_view(),
         name='create_vote'),
    path('movie/<int:movie_id>/vote/<int:pk>/', views.UpdateVote.as_view(),
         name='update_vote'),
    path('movie/<int:movie_id>/image/upload', views.MovieImageUpload.as_view(),
         name='movie_image_upload'),
    path('person/<int:pk>/', views.PersonDetail.as_view(), name='person_detail'),
]

mymdb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


MEDIA_FILE_PATHS = static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls', namespace='user')),
    path('', include('core.urls', namespace='core')),
] + MEDIA_FILE_PATHS

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
          crossorigin="anonymous">
    <title>
        {% block title %}MyMDB{% endblock %}
    </title>
    <style>
        .mymdb-masthead {
          background-color: #EEEEEE;
          margin-bottom: 1em;
        }
    </style>
</head>
<body>
    <div class="mymdb-masthead">
        <div class="container">
            <nav class="nav">
                <div class="navbar-brand">MyMDB</div>
                <a class="nav-link" href="{% url 'core:movie_list' %}">
                    Movies
                </a>
                <a class="nav-link" href="{% url 'core:top_movies' %}">
                    Top 10 Movies
                </a>
            </nav>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-sm-8 mymdb-main">
                {% block main %}{% endblock %}
            </div>
            <div class="col-sm-3 offset-sm-1 mymdb-sidebar">
                {% block sidebar %}{% endblock %}
            </div>
        </div>
    </div>
</body>
</html>